const dato = {
    productos:[
        {
            id:'1',
            nombre:'PC Gamer HP',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:20000,
            existencia:50,
            clasificacion:4.8,
            visitas:15,
        },
        {
            id:'2',
            nombre:'PC Gamer Gateway',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:19000,
            existencia:60,
            clasificacion:2.0,
            visitas:20,
        },
        {
            id:'3',
            nombre:'PC Gamer Sony',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:18000,
            existencia:70,
            clasificacion:5.0,
            visitas:30,
        },
        {
            id:'4',
            nombre:'PC Gamer Lenovo',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:17000,
            existencia:50,
            clasificacion:4.5,
            visitas:40,
        },
        {
            id:'5',
            nombre:'PC Gamer AZUS',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:16000,
            existencia:50,
            clasificacion:4.5,
            visitas:50,
        },
        {
            id:'6',
            nombre:'PC Gamer Apple',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:15000,
            existencia:0,
            clasificacion:4.8,
            visitas:60,
        },
    ],
};
export default dato;