const dato = {
    productos:[
        {
            id:'1',
            nombre:'PC Gamer HP',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:20000,
            Existencia:50,
            clasificacion: 4.5,
            visitas: 10,
        },
        {
            id:'2',
            nombre:'PC Gamer Gateway',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:19000,
            Existencia:60,
            clasificacion: 4.5,
            visitas: 10,
        },
        {
            id:'3',
            nombre:'PC Gamer Sony',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:18000,
            Existencia:70,
            clasificacion: 4.5,
            visitas: 10,
        },
        {
            id:'4',
            nombre:'PC Gamer Lenovo',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:17000,
            Existencia:50,
            clasificacion: 4.5,
            visitas: 10,
        },
        {
            id:'5',
            nombre:'PC Gamer AZUS',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:16000,
            Existencia:50,
            clasificacion: 4.5,
            visitas: 10,
        },
        {
            id:'6',
            nombre:'PC Gamer Apple',
            categoria:'Computo',
            imagen:'/imagenes/pro1.jpg',
            precio:15000,
            Existencia:50,
            clasificacion: 4.8,
            visitas: 10,
        },
    ],
};
export default dato;